# -*- coding: utf-8 -*-
"""Inference_fns

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gtEyI0DrfZVDxgsIGqETSfGBeIPuvqU4
"""
import pandas as pd
from tqdm import tqdm
import torch
from torchtext.data.utils import get_tokenizer
from DataLoader_fns import get_indices
from sklearn.metrics import classification_report, f1_score, mean_squared_error

def get_accuracy(dataloader, model):
    pred_arr = []
    target_arr = []
    model.eval()
    with torch.no_grad():
        for batch in tqdm(dataloader):
            output, scores = model(batch['indices'])
            pred = torch.argmax(output, axis=1).tolist()
            pred_arr.extend(pred)
            target_arr.extend(batch['category'].tolist())

    model.train()
    f1 = f1_score(target_arr, pred_arr)
    clr = classification_report(target_arr, pred_arr)
    print("F1: {}".format(f1))
    print(clr)
    return f1
